const FEED_URL = "https://rm-static.djicdn.com/live_json/live_game_info.json";
const REFRESH_INTERVAL_MS = 15000;

const refs = {};
const LAYOUTS = [
  { id: "one-plus", label: "1 大 + N 小", mainCount: 1, defaultRes: "high" },
  { id: "two-main", label: "2 大并排 + N 小", mainCount: 2, defaultRes: "high" },
  { id: "four-main", label: "4 大四宫格 + N 小", mainCount: 4, defaultRes: "middle" },
  { id: "grid-4x4", label: "4×4 全小视角", mainCount: 0, defaultRes: "low" },
];

const state = {
  zones: [], eventName: "赛事多视角监看系统", selectedZoneId: "", selectedStreamId: "", filter: "",
  lastUpdatedAt: null, mainHls: null, mainLoadedUrl: "", thumbHls: new Map(), refreshTimer: null,
  mainMuted: true, isLoading: false, layout: "one-plus", mainResolution: "high",
};
const RESOLUTION_RANK = { low: 1, middle: 2, medium: 2, high: 3 };

document.addEventListener("DOMContentLoaded", () => { bindRefs(); bindEvents(); renderLayoutOptions(); renderResolutionOptions(); renderIcons(); loadFeed(); state.refreshTimer = window.setInterval(loadFeed, REFRESH_INTERVAL_MS); });
function bindRefs(){["eventTitle","feedStatus","refreshButton","zoneSelect","viewFilter","layoutSelect","mainResolutionSelect","viewerLayout","lastUpdated","sourceCount","mainVideo","mainZone","mainTitle","mainQuality","mainError","retryMainButton","muteButton","thumbGrid","emptyState"].forEach((id)=>{refs[id]=document.getElementById(id);});}
function bindEvents(){refs.refreshButton.addEventListener("click",loadFeed);refs.retryMainButton.addEventListener("click",()=>{state.mainLoadedUrl="";updateMainPlayer();});refs.zoneSelect.addEventListener("change",(e)=>{state.selectedZoneId=e.target.value;state.selectedStreamId="";render();});refs.viewFilter.addEventListener("input",(e)=>{state.filter=e.target.value.trim().toLowerCase();renderThumbs();});refs.layoutSelect.addEventListener("change",(e)=>{state.layout=e.target.value;applyLayoutConfig();render();});refs.mainResolutionSelect.addEventListener("change",(e)=>{state.mainResolution=e.target.value;state.mainLoadedUrl="";updateMainPlayer();renderThumbs();});refs.muteButton.addEventListener("click",()=>{state.mainMuted=!state.mainMuted;refs.mainVideo.muted=state.mainMuted;refs.muteButton.innerHTML=state.mainMuted?'<i data-lucide="volume-x" aria-hidden="true"></i>':'<i data-lucide="volume-2" aria-hidden="true"></i>';renderIcons();});}
function renderLayoutOptions(){refs.layoutSelect.innerHTML=LAYOUTS.map(l=>`<option value="${l.id}">${l.label}</option>`).join("");refs.layoutSelect.value=state.layout;applyLayoutConfig();}
function renderResolutionOptions(){refs.mainResolutionSelect.innerHTML=`<option value="high">1080p（优先）</option><option value="middle">720p</option><option value="low">540p（省流）</option>`;refs.mainResolutionSelect.value=state.mainResolution;}
function applyLayoutConfig(){const layout=LAYOUTS.find(x=>x.id===state.layout);if(layout && state.layout!=="one-plus"){state.mainResolution=layout.defaultRes;refs.mainResolutionSelect.value=state.mainResolution;}refs.viewerLayout.dataset.layout=state.layout;}
async function loadFeed(){if(state.isLoading)return;state.isLoading=true;setFeedStatus("warn","正在更新");try{const r=await fetch(`${FEED_URL}?_=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();const parsed=parseLiveInfo(p);state.zones=parsed.zones;state.eventName=parsed.eventName||"赛事多视角监看系统";state.lastUpdatedAt=new Date();reconcileSelection();render();setFeedStatus("ok","已连接实时源");}catch(e){console.error(e);setFeedStatus("error","实时源更新失败");refs.mainError.hidden=false;}finally{state.isLoading=false;}}
function parseLiveInfo(payload){const zones=Array.isArray(payload?.eventData)?payload.eventData.map((zone,zi)=>{const zoneId=String(zone.zoneId??zi);const zoneName=zone.zoneName||`赛区 ${zi+1}`;const streams=[];if(Array.isArray(zone.zoneLiveString)&&zone.zoneLiveString.length>0){streams.push({id:`${zoneId}:main`,kind:"main",zoneId,zoneName,title:`${zoneName} 主视角`,shortTitle:"主视角",sources:normalizeSources(zone.zoneLiveString)});}if(Array.isArray(zone.fpvData)){zone.fpvData.forEach((item,si)=>{const role=item.role||`第一视角 ${si+1}`;streams.push({id:`${zoneId}:fpv:${si}`,kind:"fpv",zoneId,zoneName,title:role,shortTitle:role,sources:normalizeSources(item.sources)});});}return{zoneId,zoneName,streams:streams.filter(s=>s.sources.length>0)};}):[];return{eventName:payload?.eventName||"赛事多视角监看系统",zones};}
function normalizeSources(s=[]){return s.filter(x=>x&&x.src).map(x=>({label:x.label||labelFromRes(x.res),src:x.src,res:x.res||resFromLabel(x.label),rank:rankSource(x)})).sort((a,b)=>b.rank-a.rank);}
const labelFromRes=(res)=>res==="high"?"1080p":(res==="middle"||res==="medium")?"720p":res==="low"?"540p":"HLS";
function resFromLabel(label=""){const v=String(label).toLowerCase();if(v.includes("1080"))return"high";if(v.includes("720"))return"middle";if(v.match(/540|480|360/))return"low";return"";}
function rankSource(source){const byRes=RESOLUTION_RANK[String(source.res||"").toLowerCase()];if(byRes)return byRes;return resFromLabel(source.label)?RESOLUTION_RANK[resFromLabel(source.label)]:0;}
function pickSource(stream, mode){if(!stream?.sources?.length)return null;if(mode==="thumb")return stream.sources.find(s=>s.rank===1)||stream.sources[stream.sources.length-1];const prefer=RESOLUTION_RANK[state.mainResolution]||3;return stream.sources.find(s=>s.rank===prefer)||stream.sources[0];}
function reconcileSelection(){if(!state.zones.length){state.selectedZoneId="";state.selectedStreamId="";return;}if(!state.zones.some(z=>z.zoneId===state.selectedZoneId)){state.selectedZoneId=(state.zones.find(z=>z.streams.length>0)||state.zones[0]).zoneId;}const zone=getSelectedZone();if(!zone?.streams.some(s=>s.id===state.selectedStreamId)){state.selectedStreamId=zone?.streams[0]?.id||"";}}
function render(){refs.eventTitle.textContent=state.eventName;renderZones();renderMeta();updateMainPlayer();renderThumbs();renderIcons();}
function renderZones(){refs.zoneSelect.innerHTML=state.zones.map(z=>`<option value="${escapeAttr(z.zoneId)}" ${z.zoneId===state.selectedZoneId?"selected":""}>${escapeHtml(z.zoneName)} (${z.streams.length})</option>`).join("");refs.zoneSelect.disabled=!state.zones.length;}
function renderMeta(){const c=getSelectedZone()?.streams.length||0;refs.sourceCount.textContent=`${c} 路信号`;refs.lastUpdated.textContent=state.lastUpdatedAt?`更新于 ${state.lastUpdatedAt.toLocaleTimeString()}`:"尚未更新";}
function updateMainPlayer(){const stream=getSelectedStream();if(!stream){destroyMainPlayer();refs.mainTitle.textContent="没有可播放的直播源";refs.mainError.hidden=false;return;}const source=pickSource(stream,"main");refs.mainTitle.textContent=stream.title;refs.mainZone.textContent=stream.zoneName;refs.mainQuality.textContent=source?.label||"--";if(!source){refs.mainError.hidden=false;return;}if(state.mainLoadedUrl===source.src){refs.mainError.hidden=true;return;}state.mainLoadedUrl=source.src;refs.mainVideo.muted=state.mainMuted;refs.mainError.hidden=true;attachHls(refs.mainVideo,source.src,"main");}
function getThumbStreams(){const zone=getSelectedZone();if(!zone)return[];const layout=LAYOUTS.find(l=>l.id===state.layout);const mainCount=layout?.mainCount??1;const streams=zone.streams.filter(s=>!state.filter||(`${s.title} ${s.zoneName}`).toLowerCase().includes(state.filter));const selectedIndex=Math.max(0,streams.findIndex(s=>s.id===state.selectedStreamId));const mains=mainCount===0?[]:streams.slice(selectedIndex,selectedIndex+mainCount);if(mains[0])state.selectedStreamId=mains[0].id;const mainIds=new Set(mains.map(s=>s.id));return streams.filter(s=>!mainIds.has(s.id));}
function renderThumbs(){const thumbs=getThumbStreams();destroyMissingThumbPlayers(new Set(thumbs.map(s=>s.id)));refs.emptyState.hidden=thumbs.length>0;refs.thumbGrid.innerHTML=thumbs.map(stream=>{const source=pickSource(stream,"thumb");return `<button class="thumb-card" type="button" data-stream-id="${escapeAttr(stream.id)}"><div class="video-frame thumb-video"><video muted autoplay playsinline preload="metadata" data-video-id="${escapeAttr(stream.id)}"></video></div><span class="thumb-title">${escapeHtml(stream.shortTitle)}</span><span class="thumb-meta"><span>${escapeHtml(stream.kind==="main"?"主视角":"第一视角")}</span><span>${escapeHtml(source?.label||"--")}</span></span></button>`;}).join("");refs.thumbGrid.querySelectorAll('.thumb-card').forEach(b=>b.addEventListener('click',()=>{state.selectedStreamId=b.dataset.streamId||"";render();}));thumbs.forEach(stream=>{const source=pickSource(stream,"thumb");const video=refs.thumbGrid.querySelector(`video[data-video-id="${cssEscape(stream.id)}"]`);if(video&&source)attachHls(video,source.src,stream.id);});}
const getSelectedZone=()=>state.zones.find(z=>z.zoneId===state.selectedZoneId)||null;const getSelectedStream=()=>getSelectedZone()?.streams.find(s=>s.id===state.selectedStreamId)||null;
function attachHls(video,src,key){if(!video||!src)return;const prev=key==="main"?state.mainHls:state.thumbHls.get(key);if(prev)prev.destroy();video.pause();video.removeAttribute("src");video.load();if(video.canPlayType("application/vnd.apple.mpegurl")){video.src=src;video.play().catch(()=>{});if(key==="main")state.mainHls=null;return;}if(!window.Hls?.isSupported()){if(key==="main")refs.mainError.hidden=false;return;}const hls=new window.Hls({lowLatencyMode:true,liveSyncDurationCount:3,maxBufferLength:key==="main"?30:8,maxMaxBufferLength:key==="main"?45:12});hls.on(window.Hls.Events.ERROR,(_e,data)=>{if(data.fatal){if(key==="main")refs.mainError.hidden=false;hls.destroy();}});hls.loadSource(src);hls.attachMedia(video);hls.on(window.Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));if(key==="main")state.mainHls=hls;else state.thumbHls.set(key,hls);}
function destroyMainPlayer(){if(state.mainHls){state.mainHls.destroy();state.mainHls=null;}state.mainLoadedUrl="";refs.mainVideo.pause();refs.mainVideo.removeAttribute("src");refs.mainVideo.load();}
function destroyMissingThumbPlayers(ids){for(const [id,hls] of state.thumbHls.entries()){if(!ids.has(id)){hls.destroy();state.thumbHls.delete(id);}}}
function setFeedStatus(kind,msg){refs.feedStatus.className=`status-pill ${kind}`;refs.feedStatus.innerHTML=`<span class="status-dot"></span><span>${escapeHtml(msg)}</span>`;}
function renderIcons(){if(window.lucide)window.lucide.createIcons();}
const escapeHtml=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const escapeAttr=escapeHtml;const cssEscape=(v)=>window.CSS?.escape?window.CSS.escape(v):String(v).replace(/["\\]/g,"\\$&");
